# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2f8ad6a14c165dea6e8350ea8c46584ec4a9c9ea12f089c170d841be8c0d0d6110ec9c9f18ca87a953f8f7faafcc25ba65055e8a3611857dfc7501e249f9f9a

test:
  secret_key_base: c076520ce08859412c839ca607b572909b0fd8b6bf91ea9d0b084981641029bd0fdf03a96f77f021b26d9cdc403613e6a3dca8687b896f93b293b77b158df136

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
